### ISSUE TITLE
Markdown语法:在新窗口新标签页中打开 - 个人笔记

### ISSUE THREAD

**Issue by jp0id** [Jv0id/jv0id.github.io#2]
https://8void.cn/2019/09/07/Markdown%E8%AF%AD%E6%B3%95-%E5%9C%A8%E6%96%B0%E7%AA%97%E5%8F%A3%E6%96%B0%E6%A0%87%E7%AD%BE%E9%A1%B5%E4%B8%AD%E6%89%93%E5%BC%80/

**Comment by Jv0id** [comment]
测试评论。
